import Foundation

// English is the stable lookup key. User content is never translated.
func HL(_ key: String) -> String {
    let language = UserDefaults.standard.string(forKey: "hanjime.language") ?? "ko"
    let english = key.replacingOccurrences(of: "Atoll", with: "HanjiME Notch")
    return language == "ko" ? (hanjiMEKorean[key] ?? english) : english
}
private let hanjiMEKorean: [String: String] = [
    "Focus state file could not be decoded. Retry after changing Focus.": "집중 상태 파일을 해석하지 못했습니다. 집중 모드 전환 후 다시 확인합니다.",
    "Language": "언어",
    "Agents": "코드 작업",
    "Weather": "날씨",
    "Voice": "받아쓰기",
    "Hourly": "시간별",
    "Daily": "일별",
    "City": "도시",
    "Celsius": "섭씨 표시",
    "Refresh weather": "날씨 새로고침",
    "Weather unavailable. Check the city and connection.": "날씨를 가져오지 못했습니다. 도시 이름과 연결을 확인하세요.",
    "Choose a city in Weather settings, then refresh.": "날씨 설정에서 도시를 선택하고 새로고침하세요.",
    "City searches and forecasts use Open-Meteo. Your current location is not accessed.": "도시 검색과 예보는 Open-Meteo를 이용합니다. 현재 위치에 접근하지 않습니다.",
    "Record": "녹음 시작",
    "On-device only": "이 Mac에서만 인식",
    "Allow speech recognition in Privacy settings.": "개인정보 보호 설정에서 음성 인식을 허용하세요.",
    "Allow microphone access in Privacy settings.": "개인정보 보호 설정에서 마이크 접근을 허용하세요.",
    "On-device recognition is unavailable for this language. No audio was sent online.": "이 언어의 기기 내 인식을 사용할 수 없습니다. 음성은 온라인으로 보내지 않았습니다.",
    "Microphone unavailable": "마이크를 사용할 수 없습니다",
    "Recognition ended. Try recording again.": "인식이 끝났습니다. 다시 녹음해 주세요.",
    "Focus history": "집중 기록",
    "Save completed sessions locally": "완료 세션을 이 Mac에 기록",
    "Period": "기간",
    "Week": "주",
    "Month": "월",
    "Year": "년",
    "All": "전체",
    "Delete session history": "집중 기록 삭제",
    "Delete session history?": "집중 기록을 모두 삭제할까요?",
    "Focus background audio": "집중 배경음",
    "Brown noise": "브라운 노이즈",
    "White noise": "화이트 노이즈",
    "Generated on this Mac. Automatically quiet while music is playing.": "이 Mac에서 소리를 생성합니다. 음악이 재생되면 자동으로 조용해집니다.",
    "Could not start background audio": "배경음을 시작하지 못했습니다",
    "Activities during focus timer": "집중 타이머 중 표시할 활동",
    "Code activity": "코드 작업",
    "These filters apply only during a running Pomodoro focus phase.": "뽀모도로 집중 시간이 진행 중일 때만 적용합니다.",
    "Show local task events": "로컬 작업 이벤트 표시",
    "Only reads the dedicated event file. Does not access accounts, conversations, or approve commands.": "전용 이벤트 파일만 읽습니다. 계정·대화에 접근하거나 명령을 승인하지 않습니다.",
    "Code activity file could not be read": "코드 작업 이벤트 파일을 읽지 못했습니다",
    "Copy event file path": "이벤트 파일 경로 복사",
    "Thinking": "생각 중",
    "Working": "작업 중",
    "Completed": "완료",
    "Failed": "실패",
    "Cycle outputs with ⌃⌥⌘O": "⌃⌥⌘O로 오디오 출력 순환",
    "Focus sharing alone may not expose every mode. Full Disk Access allows reading the actual mode, icon, and color.": "상태 공유만으로는 모든 모드를 확인할 수 없습니다. 전체 디스크 접근을 허용하면 실제 모드·아이콘·색상을 읽을 수 있습니다.",

    "Audio output": "오디오 출력 장치",
    "Refresh audio outputs": "출력 장치 새로고침",
    "Could not switch audio output": "출력 장치를 변경하지 못했습니다",
    "Show Focus changes in the notch": "집중 모드 켜짐·꺼짐을 노치에 표시",
    "Focus is on": "집중 모드 켜짐",
    "Focus is off": "집중 모드 꺼짐",
    "Focus status unavailable": "집중 모드 상태 확인 대기",
    "Allow Focus status access": "집중 모드 상태 접근 허용",
    "Requires Focus status sharing. Shows on/off changes; the system does not provide the mode name.": "집중 모드 상태 공유가 필요합니다. 켜짐·꺼짐을 표시하며 모드 이름은 제공되지 않습니다.",
    "Focus task": "집중할 작업 · 기록",
    "What are you working on?": "지금 집중할 작업",
    "Remind me of my task every 5 minutes": "5분마다 작업을 노치에 표시",
    "Completed focus sessions": "완료한 집중 세션",
    "Completed focus time": "완료한 집중 시간",
    "Only fully completed focus phases count. Records stay on this Mac.": "끝까지 완료한 집중 단계만 집계합니다. 기록은 이 Mac에 저장됩니다.",
    "minutes": "분",
    "Keep display awake during focus": "집중 중 화면 꺼짐 방지",
    "Only during a running focus phase. Pausing, taking a break, or ending the session restores normal display sleep.": "집중 시간이 진행 중일 때만 적용됩니다. 일시 정지·휴식·종료 시 원래 화면 꺼짐 동작으로 돌아갑니다.",
    "Show completed tasks": "완료한 할 일 표시",
    "A banner is posted when a timer finishes — even if Atoll was quit.": "앱을 종료해도 예약된 타이머 완료 알림이 표시됩니다.",
    "Accent": "강조",
    "Accent color": "강조 색상",
    "Accessibility access is required to intercept media keys": "미디어 키를 처리하려면 손쉬운 사용 권한이 필요합니다",
    "Add a to-do…": "새 할 일…",
    "After 1 hour": "1시간 후",
    "After 1 week": "1주 후",
    "After 12 hours": "12시간 후",
    "After 2 days": "2일 후",
    "After 24 hours": "24시간 후",
    "After 6 hours": "6시간 후",
    "Agent sessions": "에이전트 세션",
    "All clear": "모두 완료했습니다",
    "All-day": "하루 종일",
    "Allow Automation access": "자동화 접근 허용",
    "Allow notifications to get a banner when a timer finishes.": "타이머 완료 배너를 받으려면 알림을 허용하세요.",
    "Also shows the notch HUD when volume or mute is changed by another app, AirPods, an external keyboard, or the menu-bar slider.": "다른 앱·AirPods·외부 키보드·메뉴 막대에서 음량이나 음소거를 바꿀 때도 노치에 표시합니다.",
    "Always show percentage": "잔량 백분율 항상 표시",
    "Any app": "모든 앱",
    "Appearance": "모양",
    "Archive": "보관",
    "Archived": "보관됨",
    "Archived items": "보관된 항목",
    "Atoll needs full Calendar access to show your events. Grant it under Privacy & Security \u{203A} Calendars.": "일정을 표시하려면 캘린더 전체 접근이 필요합니다. 개인정보 보호 및 보안의 캘린더에서 허용하세요.",
    "Audio visualizer in the notch": "노치에 오디오 시각 효과 표시",
    "Auto-archive completed": "완료 항목 자동 보관",
    "Automatic": "자동",
    "Background": "배경",
    "Battery": "배터리",
    "Battery & charging": "배터리 및 충전",
    "Battery live activity": "배터리 실시간 활동",
    "Behavior": "동작",
    "Bluetooth": "블루투스",
    "Bluetooth access is disabled for Atoll, so device events can't be detected.": "블루투스 접근이 꺼져 있어 기기 연결 변화를 감지할 수 없습니다.",
    "Bluetooth live activity": "블루투스 실시간 활동",
    "Border glow": "테두리 빛 효과",
    "Break": "휴식",
    "Calendar": "일정",
    "Calendar access": "캘린더 접근",
    "Calendar only": "일정만",
    "Calendars": "캘린더",
    "Camera access": "카메라 접근",
    "Camera access is currently disabled for Atoll, so the mirror can't show a preview.": "카메라 접근이 꺼져 있어 거울 영상을 표시할 수 없습니다.",
    "Cancel": "취소",
    "Clear Archive": "보관된 항목 지우기",
    "Clear shelf when quitting": "종료할 때 보관함 비우기",
    "Closed-notch live activities": "접힌 노치의 실시간 활동",
    "Completed to-dos stay visible (struck through) until the auto-archive delay passes, then move to the archive.": "완료한 할 일은 취소선으로 표시되며, 설정한 시간이 지나면 보관함으로 이동합니다.",
    "Completion": "완료",
    "Connected now": "현재 연결됨",
    "Copy Text": "텍스트 복사",
    "Corner radius": "모서리 둥글기",
    "Countdown": "카운트다운",
    "Default camera": "기본 카메라",
    "Default tab": "기본 탭",
    "Delete": "삭제",
    "Deselect All": "선택 해제",
    "Displays": "디스플레이",
    "Done": "완료",
    "Drop files here": "여기에 파일을 놓으세요",
    "Duplicate": "복제",
    "Editor": "편집기",
    "Enable": "켜기",
    "Enable Notifications": "알림 켜기",
    "Enable\u{2026}": "켜기…",
    "Events": "일정",
    "External changes": "외부 변경",
    "Files, links and text land on the shelf.": "파일·링크·텍스트를 보관할 수 있습니다.",
    "Filter shortcuts": "단축어 검색",
    "Flip preview horizontally (mirror)": "좌우 반전 · 거울 모드",
    "Font size": "글자 크기",
    "General": "일반",
    "Gradient": "그라데이션",
    "Gradient bottom": "아래쪽 색상",
    "Gradient top": "위쪽 색상",
    "Grant Access…": "접근 허용…",
    "Face recognition": "얼굴인식",
    "HUD": "시스템 표시",
    "Haptic feedback": "햅틱 반응",
    "Height": "높이",
    "Hide all-day events": "하루 종일 일정 숨기기",
    "Hide from Widget": "위젯에서 숨기기",
    "Hide multi-day events": "여러 날에 걸친 일정 숨기기",
    "Hiding a shortcut only removes it from the notch widget — it stays available in the Shortcuts app.": "숨긴 단축어는 노치에서만 사라지며, 단축어 앱에는 그대로 남습니다.",
    "Home": "홈",
    "Home tab": "홈 탭",
    "Hours": "시간",
    "Hover delay": "열기 지연",
    "Items stay on the shelf across restarts unless cleared. Files are referenced in place — dropped data and pasted images are stored in Atoll's Application Support folder.": "보관함 항목은 앱을 다시 실행해도 유지됩니다. 원본 파일은 이동하지 않으며 붙여넣은 이미지와 데이터만 앱 전용 폴더에 저장합니다.",
    "Last selected camera (disconnected)": "마지막 선택 카메라 · 연결 끊김",
    "Launch at login": "로그인 시 실행",
    "Layout": "배치",
    "Live Activities": "실시간 활동",
    "Loading shortcuts…": "단축어 불러오는 중…",
    "Low battery alerts": "배터리 부족 알림",
    "Media": "미디어",
    "Media + Calendar": "미디어 + 일정",
    "Media controls are off": "미디어 제어가 꺼져 있습니다",
    "Media only": "미디어만",
    "MediaRemote adapter not bundled — only Spotify / Apple Music will be detected": "미디어 연결 구성 요소가 없어 음악 및 Spotify만 감지됩니다",
    "Minutes": "분",
    "Mirror": "거울",
    "Never": "사용 안 함",
    "New Note": "새 메모",
    "No events": "일정 없음",
    "No notes yet": "아직 메모가 없습니다",
    "No shortcuts found.": "단축어가 없습니다.",
    "Note list": "메모 목록",
    "Notes": "메모",
    "Nothing playing": "재생 중인 미디어 없음",
    "Notifications": "알림",
    "Notifications are turned off for Atoll.": "한지미 노치 알림이 꺼져 있습니다.",
    "Notifications require the bundled Atoll.app build.": "알림은 앱 번들로 실행할 때 사용할 수 있습니다.",
    "Now Playing": "재생 중",
    "Now playing": "재생 중인 미디어",
    "Only events from selected calendars appear in the notch.": "선택한 캘린더의 일정만 노치에 표시합니다.",
    "Open Privacy Settings…": "개인정보 보호 설정 열기…",
    "Open Settings": "설정 열기",
    "Open Shortcuts App": "단축어 앱 열기",
    "Open System Settings": "시스템 설정 열기",
    "Open System Settings…": "시스템 설정 열기…",
    "Open nook size": "펼친 노치 크기",
    "Open on hover": "커서를 올리면 열기",
    "Open shelf when dragging files toward the notch": "파일을 노치로 끌어오면 보관함 열기",
    "Open the notch when a timer completes": "타이머가 끝나면 노치 열기",
    "Open to-dos count": "남은 할 일 개수",
    "Paste from Clipboard": "클립보드에서 붙여넣기",
    "Pause": "일시 정지",
    "Permission": "권한",
    "Play something in Music, Spotify, or your browser": "음악·Spotify·브라우저에서 미디어를 재생하세요",
    "Pomodoro": "뽀모도로",
    "Press Return to add a to-do": "Return을 눌러 할 일을 추가하세요",
    "Pure black": "검정",
    "Quit Atoll": "한지미 노치 종료",
    "Refresh": "새로고침",
    "Remove items after dragging them out": "밖으로 끌어낸 항목은 보관함에서 제거",
    "Replace system HUD": "기본 시스템 표시 대체",
    "Reset": "초기화",
    "Restore": "복원",
    "Resume": "계속",
    "Reveal Notes File in Finder": "Finder에서 메모 파일 보기",
    "Search": "검색",
    "Seconds": "초",
    "Select All": "모두 선택",
    "Settings…": "설정…",
    "Shelf": "파일 보관함",
    "Shortcuts": "단축어",
    "Shortcuts widget": "단축어 위젯",
    "Show All": "모두 표시",
    "Show HUD when volume changes externally": "다른 앱에서 음량을 바꿀 때 표시",
    "Show all": "모두 표시",
    "Show archived section in widget": "위젯에 보관된 항목 표시",
    "Show media controls": "미디어 제어 표시",
    "Show media from": "미디어 앱 선택",
    "Show on all displays": "모든 디스플레이에 표시",
    "Shown in widget": "위젯에 표시됨",
    "Shows charging, unplugged, fully charged and low battery (20% / 10%) events beside the notch. Low Power Mode changes are shown too.": "충전·전원 분리·충전 완료·배터리 부족(20% / 10%)과 저전력 모드 변경을 노치에 표시합니다.",
    "Shows device connect and disconnect events beside the notch.": "기기 연결 및 연결 해제를 노치에 표시합니다.",
    "Simulate notch on external displays": "외부 디스플레이에 가상 노치 표시",
    "Sort notes by": "메모 정렬",
    "Sound": "소리",
    "Start": "시작",
    "Start next phase automatically": "다음 구간 자동 시작",
    "Start typing…": "내용을 입력하세요…",
    "Status": "상태",
    "Stop": "중지",
    "Stopwatch": "스톱워치",
    "Storage": "저장",
    "Style": "스타일",
    "System": "시스템",
    "System HUD": "시스템 표시",
    "Tabs": "탭",
    "Timers": "타이머",
    "Tinted by artwork": "앨범 이미지 색상 적용",
    "To-dos": "할 일",
    "Today": "오늘",
    "Toggle shortcut": "열기·닫기 단축키",
    "Tools": "도구",
    "Upcoming calendar event": "다가오는 일정",
    "Version": "버전",
    "Volume, brightness and mute changes appear inside the notch instead of the system bezel. Media keys are intercepted while this is on; turning it off restores the standard macOS HUD immediately.": "음량·밝기·음소거 변경을 노치에 표시합니다. 켜져 있는 동안 미디어 키를 처리하며, 끄면 macOS 기본 표시로 돌아갑니다.",
    "Width": "너비",
    "Work": "집중",
    "Unpin the nook": "고정 해제",
    "Keep the nook open": "노치 펼침 유지",
    "Atoll Settings": "한지미 노치 설정",
    "Close Nook": "노치 닫기",
    "Open Nook": "노치 열기",
    "Preview the selected sound": "선택한 소리 미리 듣기",
    "New note": "새 메모",
    "Copy note": "메모 복사",
    "Delete note": "메모 삭제",
    "Jot something down": "간단한 메모를 남겨 보세요",
    "No note selected": "선택한 메모 없음",
    "just now": "방금",
    "Previous day": "이전 날짜",
    "Next day": "다음 날짜",
    "See your day at a glance right in the notch.": "노치에서 오늘 일정을 확인하세요.",
    "Enable Calendar Access": "캘린더 접근 허용",
    "Calendar access is turned off. Grant full access in System Settings to see your events.": "캘린더 접근이 꺼져 있습니다. 시스템 설정에서 전체 접근을 허용하세요.",
    "Untitled Event": "제목 없는 일정",
    "Open in Calendar": "캘린더에서 열기",
    "not yet asked": "요청 전",
    "Collapse into stack": "겹쳐서 보기",
    "Show all items": "모든 항목 보기",
    "Paste from clipboard": "클립보드에서 붙여넣기",
    "Clear shelf": "보관함 비우기",
    "Expand the stack": "펼쳐서 보기",
    "Quick Look": "훑어보기",
    "Reveal in Finder": "Finder에서 보기",
    "Drop files, links or text to AirDrop them": "파일·링크·텍스트를 놓아 AirDrop으로 보내세요",
    "AirDrop drop zone": "AirDrop 놓기 영역",
    "Mark as open": "미완료로 변경",
    "Mark as done": "완료로 변경",
    "Remove from favorites": "즐겨찾기 해제",
    "Pin to top": "맨 위에 고정",
    "Mark as Open": "미완료로 변경",
    "Mark as Done": "완료로 변경",
    "Remove Favorite": "즐겨찾기 해제",
    "Delete permanently": "영구 삭제",
    "Show unmirrored": "좌우 반전 끄기",
    "Show mirrored": "거울 모드 켜기",
    "Choose camera": "카메라 선택",
    "Camera access needed": "카메라 접근 필요",
    "Atoll uses the camera only to show this mirror.": "카메라는 거울 영상을 보여줄 때만 사용합니다.",
    "Enable Camera": "카메라 켜기",
    "Camera access is off": "카메라 접근이 꺼져 있습니다",
    "Allow camera access for Atoll in System Settings to use the mirror.": "거울을 사용하려면 시스템 설정에서 한지미 노치의 카메라 접근을 허용하세요.",
    "No camera found": "카메라를 찾지 못했습니다",
    "Connect a webcam, or bring your iPhone nearby to use Continuity Camera.": "웹캠을 연결하거나 연속성 카메라를 사용할 iPhone을 가까이 두세요.",
    "Could not install the media-key event tap. Try toggling the setting off and on, or relaunch Atoll.": "미디어 키 처리를 시작하지 못했습니다. 설정을 껐다 켜거나 앱을 다시 실행하세요.",
    "Display brightness control is unavailable on this Mac; brightness keys are passed through to the system.": "이 Mac에서는 밝기를 제어할 수 없어 밝기 키를 시스템에 그대로 전달합니다.",
    "Accessibility access granted": "손쉬운 사용 접근 허용됨",
    "Unknown title": "제목 없음",
    "MediaRemote adapter available": "전체 미디어 연결 사용 가능",
    "MediaRemote adapter not bundled — using app-specific fallback only": "전체 미디어 연결이 없어 앱별 연결을 사용합니다",
    "Automation access denied for Spotify / Music": "Spotify 또는 음악 앱의 자동화 접근이 거부되었습니다",
    "Refresh shortcut list": "단축어 목록 새로고침",
    "Shortcuts Unavailable": "단축어 사용 불가",
    "Try Again": "다시 시도",
    "Couldn't Load Shortcuts": "단축어를 불러오지 못했습니다",
    "No Shortcuts Yet": "아직 단축어가 없습니다",
    "Create shortcuts in the Shortcuts app and they will show up here.": "단축어 앱에서 만든 단축어가 여기에 표시됩니다.",
    "Open Shortcuts": "단축어 열기",
    "All Shortcuts Hidden": "모든 단축어가 숨겨져 있습니다",
    "Every shortcut is hidden. Show some again from Atoll settings.": "설정에서 사용할 단축어를 다시 표시하세요.",
    "Unhide All": "모두 다시 표시",
    "No Matches": "검색 결과 없음",
    "Clear Search": "검색 지우기",
    "Remove from Favorites": "즐겨찾기 해제",
    "Add to Favorites": "즐겨찾기에 추가",
    "Favorite — floats to the top": "즐겨찾기 · 맨 위에 표시",
    "Loading shortcut list…": "단축어 목록 불러오는 중…",
    "Shortcuts CLI not found on this Mac": "이 Mac에서 단축어 실행 도구를 찾지 못했습니다",
    "Couldn't read the shortcut list": "단축어 목록을 읽지 못했습니다",
    "Add to favorites": "즐겨찾기에 추가",
    "Timer": "타이머",
    "Focus": "집중",
    "Long Break": "긴 휴식"
]
